### List employees
GET http://localhost:8080/api/employees

### Create employees
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "John Doe"
}

### Update
PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "id": 1,
  "name": "Jack Doe"
}

### Delete
DELETE http://localhost:8080/api/employees/1